// src/pages/Skills.jsx
import { motion } from 'framer-motion';
import { AnimatedPage } from '../components/AnimatedPage';
import { Card } from '../components/ui/Card';
import { SkillBadge } from '../components/ui/SkillBadge';

const skillCategories = [
  {
    title: 'Programming Languages',
    skills: ['C', 'Go', 'C++', 'Java', 'Python', 'JavaScript', 'HTML/CSS', 'SQL', 'C#', 'Rust'],
  },
  {
    title: 'Tools & Technologies',
    skills: ['Docker', 'Git', 'GitHub', 'AWS', 'Azure', 'Linux', 'VS Code', 'Postman'],
  },
  {
    title: 'Frameworks & Libraries',
    skills: ['Gin', 'Angular', 'Node.js', 'Express.js', 'React', 'ASP.NET', 'Spring Boot'],
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.2,
    },
  },
};

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0 },
};

export function Skills() {
  return (
    <AnimatedPage className="skills-page">
      <section className="section">
        <div className="container">
          <h2 className="section-title">Skills & Expertise</h2>
          <p className="section-subtitle">
            Technologies and tools I've worked with throughout my journey as a developer.
          </p>

          <motion.div
            className="skills-grid"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
          >
            {skillCategories.map((category, categoryIndex) => (
              <motion.div key={category.title} variants={cardVariants}>
                <Card className="skill-card" hover={false}>
                  <h3 className="skill-category-title">{category.title}</h3>
                  <div className="skill-badges">
                    {category.skills.map((skill, skillIndex) => (
                      <SkillBadge
                        key={skill}
                        name={skill}
                        delay={categoryIndex * 0.1 + skillIndex * 0.05}
                      />
                    ))}
                  </div>
                </Card>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>
    </AnimatedPage>
  );
}

// src/app/pages/skills/skills.component.ts
import { Component, AfterViewInit, ElementRef, QueryList, ViewChildren } from '@angular/core';

const D = 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons';

@Component({
  selector: 'app-skills',
  templateUrl: './skills.component.html',
  styleUrl: './skills.component.scss'
})
export class SkillsComponent implements AfterViewInit {
  @ViewChildren('reveal') revealEls!: QueryList<ElementRef>;

  ngAfterViewInit() {
    const observer = new IntersectionObserver(
      entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')),
      { threshold: 0.1 }
    );
    this.revealEls.forEach(el => observer.observe(el.nativeElement));
  }

  categories = [
    {
      title: 'Languages',
      skills: [
        { name: 'C',          logo: `${D}/c/c-original.svg` },
        { name: 'Go',         logo: `${D}/go/go-original-wordmark.svg` },
        { name: 'C++',        logo: `${D}/cplusplus/cplusplus-original.svg` },
        { name: 'Java',       logo: `${D}/java/java-original.svg` },
        { name: 'Python',     logo: `${D}/python/python-original.svg` },
        { name: 'JavaScript', logo: `${D}/javascript/javascript-original.svg` },
        { name: 'TypeScript', logo: `${D}/typescript/typescript-original.svg` },
        { name: 'HTML',       logo: `${D}/html5/html5-original.svg` },
        { name: 'CSS',        logo: `${D}/css3/css3-original.svg` },
        { name: 'SQL',        logo: `${D}/mysql/mysql-original.svg` },
        { name: 'Rust',       logo: `${D}/rust/rust-original.svg` },
      ]
    },
    {
      title: 'Tools & Platforms',
      skills: [
        { name: 'Docker',   logo: `${D}/docker/docker-original.svg` },
        { name: 'Git',      logo: `${D}/git/git-original.svg` },
        { name: 'GitHub',   logo: `${D}/github/github-original.svg` },
        { name: 'AWS',      logo: `${D}/amazonwebservices/amazonwebservices-plain-wordmark.svg` },
        { name: 'Azure',    logo: `${D}/azure/azure-original.svg` },
        { name: 'Linux',    logo: `${D}/linux/linux-original.svg` },
        { name: 'VS Code',  logo: `${D}/vscode/vscode-original.svg` },
        { name: 'Postman',  logo: `${D}/postman/postman-original.svg` },
      ]
    },
    {
      title: 'Frameworks',
      skills: [
        { name: 'Angular',      logo: `${D}/angular/angular-original.svg` },
        { name: 'React',        logo: `${D}/react/react-original.svg` },
        { name: 'Node.js',      logo: `${D}/nodejs/nodejs-original.svg` },
        { name: 'Express.js',   logo: `${D}/express/express-original.svg` },
        { name: 'Spring Boot',  logo: `${D}/spring/spring-original.svg` },
        { name: 'ASP.NET',      logo: `${D}/dotnetcore/dotnetcore-original.svg` },
        { name: 'Gin',          logo: `${D}/go/go-original-wordmark.svg` },
      ]
    }
  ];
}

<div class="section page-enter">
  <h1 class="section-title reveal" #reveal>My <span class="gradient-text">Skills</span></h1>
  <p class="section-sub reveal delay-1" #reveal>Technologies I work with</p>

  <div class="categories">
    @for (cat of categories; track cat.title; let i = $index) {
      <div class="category reveal" #reveal [style.transition-delay]="(i * 0.15 + 0.2) + 's'">
        <h2>{{ cat.title }}</h2>
        <div class="badges">
          @for (skill of cat.skills; track skill.name) {
            <div class="badge">
              <img [src]="skill.logo" [alt]="skill.name" loading="lazy" />
              <span>{{ skill.name }}</span>
            </div>
          }
        </div>
      </div>
    }
  </div>
</div>
