// src/pages/Projects.jsx
import { AnimatedPage } from '../components/AnimatedPage';
import { ProjectCard } from '../components/ui/ProjectCard';

const projects = [
  {
    title: 'Web Server Using C',
    description:
      'A lightweight HTTP/1.0 web server built from scratch in C. Features include handling GET requests, serving static files, and proper HTTP response formatting.',
    image: '/WebServer Using C.jpg',
    github: 'https://github.com/a7medmo7amady/WebServer-C',
    technologies: ['C', 'HTTP', 'Sockets', 'Linux'],
  },
  {
    title: 'Face Detection',
    description:
      'Real-time face detection application using Python and OpenCV. Implements computer vision algorithms to detect and track faces in video streams.',
    image: '/FaceDetection.jpg',
    github: 'https://github.com/a7medmo7amady/FaceDetection',
    technologies: ['Python', 'OpenCV', 'NumPy', 'Computer Vision'],
  },
];

export function Projects() {
  return (
    <AnimatedPage className="projects-page">
      <section className="section">
        <div className="container">
          <h2 className="section-title">My Projects</h2>
          <p className="section-subtitle">
            Here are some of the projects I've worked on. Each one represents a unique
            challenge and learning experience.
          </p>

          <div className="projects-grid">
            {projects.map((project, index) => (
              <ProjectCard
                key={project.title}
                {...project}
                delay={index * 0.15}
              />
            ))}
          </div>
        </div>
      </section>
    </AnimatedPage>
  );
}

// src/app/pages/projects/projects.component.ts
import { Component, AfterViewInit, ElementRef, QueryList, ViewChildren } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.scss'
})
export class ProjectsComponent implements AfterViewInit {
  @ViewChildren('reveal') revealEls!: QueryList<ElementRef>;

  ngAfterViewInit() {
    const observer = new IntersectionObserver(
      entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')),
      { threshold: 0.1 }
    );
    this.revealEls.forEach(el => observer.observe(el.nativeElement));
  }

  projects = [
    {
      title: 'Web Server Using C',
      description: 'An HTTP/1.0 web server built from scratch in C using raw sockets and Linux system calls.',
      image: '/WebServer Using C.jpg',
      tags: ['C', 'HTTP', 'Sockets', 'Linux'],
      github: 'https://github.com/a7medmo7amady'
    },
    {
      title: 'Face Detection',
      description: 'Real-time face detection using OpenCV and Python with live webcam feed processing.',
      image: '/FaceDetection.jpg',
      tags: ['Python', 'OpenCV', 'NumPy', 'Computer Vision'],
      github: 'https://github.com/a7medmo7amady'
    }
  ];
}

<div class="section page-enter">
  <h1 class="section-title reveal" #reveal>My <span class="gradient-text">Projects</span></h1>
  <p class="section-sub reveal delay-1" #reveal>Things I've built</p>

  <div class="projects-grid">
    @for (project of projects; track project.title; let i = $index) {
      <div class="project-card card reveal" #reveal [style.transition-delay]="(i * 0.15 + 0.2) + 's'">
        <div class="image-wrap">
          <img [src]="project.image" [alt]="project.title" loading="lazy" />
          <a [href]="project.github" target="_blank" rel="noopener" class="overlay">
            <span>View on GitHub →</span>
          </a>
        </div>
        <div class="info">
          <h2>{{ project.title }}</h2>
          <p>{{ project.description }}</p>
          <div class="tags">
            @for (tag of project.tags; track tag) {
              <span class="tag">{{ tag }}</span>
            }
          </div>
        </div>
      </div>
    }
  </div>
</div>
